#!/bin/bash

set -x
mkdir -p $CRAFT_PRIME/usr/share/rocks/

{
    echo "# os-release"
    cat /etc/os-release
    echo "# dpkg-query"
    # include all packages in the system
    dpkg-query --admindir=$CRAFT_PRIME/var/lib/dpkg/ \
        -f '${db:Status-Abbrev},${binary:Package},${Version},${source:Package},${Source:Version}\n' \
        -W

    # include all .deb files in stage_packages
    for deb in /root/parts/*/stage_packages/*.deb; do 
        # TODO: should we assume that all packages are installed correctly (ii)
        dpkg-deb -W --showformat 'ii,${Package},${Version},,\n' $deb 
    done
    # include all results from chisel manifest
    zstdcat $CRAFT_STAGE/var/lib/chisel/manifest.wall | jq -r 'select(.kind == "package") | "ii," + .name + "," + .version + ",,"'

} | sort | uniq | tee $CRAFT_PRIME/usr/share/rocks/dpkg.query