name: Tests

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: [jammy, amd64, large]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        lxd init --auto  
        sudo snap install rockcraft --classic

    - name: Run Tests
      run: |
        ./tests/run_all.sh